[package]
name = "nia-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4"] }
jsonwebtoken = "8.0"
chrono = { version = "0.4", features = ["serde"] }
