version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: start --user root --pass root memory
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - surrealdb
      - redis
      
  auth-service:
    build: ./services/auth-service
    ports:
      - "50051:50051"
    depends_on:
      - surrealdb
      - redis
      
  user-service:
    build: ./services/user-service
    ports:
      - "50052:50051"
    depends_on:
      - surrealdb
      
  post-service:
    build: ./services/post-service
    ports:
      - "50053:50051" 
    depends_on:
      - surrealdb
      
  timeline-service:
    build: ./services/timeline-service
    ports:
      - "50054:50051"
    depends_on:
      - surrealdb
      
  notification-service:
    build: ./services/notification-service
    ports:
      - "50055:50051"
    depends_on:
      - surrealdb
      - redis
      
  media-service:
    build: ./services/media-service
    ports:
      - "50056:50051"
      
  moderation-service:
    build: ./services/moderation-service
    ports:
      - "50057:50051"
    depends_on:
      - surrealdb
      
  dm-service:
    build: ./services/dm-service
    ports:
      - "50058:50051"
    depends_on:
      - surrealdb
      - redis
