// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/pagination.proto

package sonet.common;

public final class PaginationOuterClass {
  private PaginationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaginationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonet.common.PaginationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    int getLimit();

    /**
     * <pre>
     * Optional cursor for pagination
     * </pre>
     *
     * <code>string cursor = 3;</code>
     * @return The cursor.
     */
    java.lang.String getCursor();
    /**
     * <pre>
     * Optional cursor for pagination
     * </pre>
     *
     * <code>string cursor = 3;</code>
     * @return The bytes for cursor.
     */
    com.google.protobuf.ByteString
        getCursorBytes();
  }
  /**
   * <pre>
   * Pagination request parameters
   * </pre>
   *
   * Protobuf type {@code sonet.common.PaginationRequest}
   */
  public static final class PaginationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sonet.common.PaginationRequest)
      PaginationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaginationRequest.newBuilder() to construct.
    private PaginationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaginationRequest() {
      cursor_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaginationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sonet.common.PaginationOuterClass.PaginationRequest.class, sonet.common.PaginationOuterClass.PaginationRequest.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_ = 0;
    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int LIMIT_FIELD_NUMBER = 2;
    private int limit_ = 0;
    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }

    public static final int CURSOR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cursor_ = "";
    /**
     * <pre>
     * Optional cursor for pagination
     * </pre>
     *
     * <code>string cursor = 3;</code>
     * @return The cursor.
     */
    @java.lang.Override
    public java.lang.String getCursor() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cursor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional cursor for pagination
     * </pre>
     *
     * <code>string cursor = 3;</code>
     * @return The bytes for cursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCursorBytes() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0) {
        output.writeInt32(1, offset_);
      }
      if (limit_ != 0) {
        output.writeInt32(2, limit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cursor_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cursor_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limit_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cursor_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cursor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sonet.common.PaginationOuterClass.PaginationRequest)) {
        return super.equals(obj);
      }
      sonet.common.PaginationOuterClass.PaginationRequest other = (sonet.common.PaginationOuterClass.PaginationRequest) obj;

      if (getOffset()
          != other.getOffset()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (!getCursor()
          .equals(other.getCursor())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getCursor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sonet.common.PaginationOuterClass.PaginationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Pagination request parameters
     * </pre>
     *
     * Protobuf type {@code sonet.common.PaginationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonet.common.PaginationRequest)
        sonet.common.PaginationOuterClass.PaginationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sonet.common.PaginationOuterClass.PaginationRequest.class, sonet.common.PaginationOuterClass.PaginationRequest.Builder.class);
      }

      // Construct using sonet.common.PaginationOuterClass.PaginationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        offset_ = 0;
        limit_ = 0;
        cursor_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationRequest_descriptor;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationRequest getDefaultInstanceForType() {
        return sonet.common.PaginationOuterClass.PaginationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationRequest build() {
        sonet.common.PaginationOuterClass.PaginationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationRequest buildPartial() {
        sonet.common.PaginationOuterClass.PaginationRequest result = new sonet.common.PaginationOuterClass.PaginationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sonet.common.PaginationOuterClass.PaginationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.offset_ = offset_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cursor_ = cursor_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sonet.common.PaginationOuterClass.PaginationRequest) {
          return mergeFrom((sonet.common.PaginationOuterClass.PaginationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sonet.common.PaginationOuterClass.PaginationRequest other) {
        if (other == sonet.common.PaginationOuterClass.PaginationRequest.getDefaultInstance()) return this;
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (!other.getCursor().isEmpty()) {
          cursor_ = other.cursor_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                offset_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                limit_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                cursor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return The limit.
       */
      @java.lang.Override
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        limit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cursor_ = "";
      /**
       * <pre>
       * Optional cursor for pagination
       * </pre>
       *
       * <code>string cursor = 3;</code>
       * @return The cursor.
       */
      public java.lang.String getCursor() {
        java.lang.Object ref = cursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cursor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional cursor for pagination
       * </pre>
       *
       * <code>string cursor = 3;</code>
       * @return The bytes for cursor.
       */
      public com.google.protobuf.ByteString
          getCursorBytes() {
        java.lang.Object ref = cursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional cursor for pagination
       * </pre>
       *
       * <code>string cursor = 3;</code>
       * @param value The cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cursor_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional cursor for pagination
       * </pre>
       *
       * <code>string cursor = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursor() {
        cursor_ = getDefaultInstance().getCursor();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional cursor for pagination
       * </pre>
       *
       * <code>string cursor = 3;</code>
       * @param value The bytes for cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cursor_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sonet.common.PaginationRequest)
    }

    // @@protoc_insertion_point(class_scope:sonet.common.PaginationRequest)
    private static final sonet.common.PaginationOuterClass.PaginationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sonet.common.PaginationOuterClass.PaginationRequest();
    }

    public static sonet.common.PaginationOuterClass.PaginationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaginationRequest>
        PARSER = new com.google.protobuf.AbstractParser<PaginationRequest>() {
      @java.lang.Override
      public PaginationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaginationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaginationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sonet.common.PaginationOuterClass.PaginationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaginationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonet.common.PaginationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    int getLimit();

    /**
     * <pre>
     * Total number of items available
     * </pre>
     *
     * <code>int32 total_count = 3;</code>
     * @return The totalCount.
     */
    int getTotalCount();

    /**
     * <pre>
     * Whether there are more items available
     * </pre>
     *
     * <code>bool has_next = 4;</code>
     * @return The hasNext.
     */
    boolean getHasNext();

    /**
     * <pre>
     * Whether there are previous items available
     * </pre>
     *
     * <code>bool has_previous = 5;</code>
     * @return The hasPrevious.
     */
    boolean getHasPrevious();

    /**
     * <pre>
     * Next cursor for pagination
     * </pre>
     *
     * <code>string next_cursor = 6;</code>
     * @return The nextCursor.
     */
    java.lang.String getNextCursor();
    /**
     * <pre>
     * Next cursor for pagination
     * </pre>
     *
     * <code>string next_cursor = 6;</code>
     * @return The bytes for nextCursor.
     */
    com.google.protobuf.ByteString
        getNextCursorBytes();

    /**
     * <pre>
     * Previous cursor for pagination
     * </pre>
     *
     * <code>string prev_cursor = 7;</code>
     * @return The prevCursor.
     */
    java.lang.String getPrevCursor();
    /**
     * <pre>
     * Previous cursor for pagination
     * </pre>
     *
     * <code>string prev_cursor = 7;</code>
     * @return The bytes for prevCursor.
     */
    com.google.protobuf.ByteString
        getPrevCursorBytes();
  }
  /**
   * <pre>
   * Pagination response information
   * </pre>
   *
   * Protobuf type {@code sonet.common.PaginationResponse}
   */
  public static final class PaginationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sonet.common.PaginationResponse)
      PaginationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaginationResponse.newBuilder() to construct.
    private PaginationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaginationResponse() {
      nextCursor_ = "";
      prevCursor_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaginationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sonet.common.PaginationOuterClass.PaginationResponse.class, sonet.common.PaginationOuterClass.PaginationResponse.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_ = 0;
    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int LIMIT_FIELD_NUMBER = 2;
    private int limit_ = 0;
    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }

    public static final int TOTAL_COUNT_FIELD_NUMBER = 3;
    private int totalCount_ = 0;
    /**
     * <pre>
     * Total number of items available
     * </pre>
     *
     * <code>int32 total_count = 3;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }

    public static final int HAS_NEXT_FIELD_NUMBER = 4;
    private boolean hasNext_ = false;
    /**
     * <pre>
     * Whether there are more items available
     * </pre>
     *
     * <code>bool has_next = 4;</code>
     * @return The hasNext.
     */
    @java.lang.Override
    public boolean getHasNext() {
      return hasNext_;
    }

    public static final int HAS_PREVIOUS_FIELD_NUMBER = 5;
    private boolean hasPrevious_ = false;
    /**
     * <pre>
     * Whether there are previous items available
     * </pre>
     *
     * <code>bool has_previous = 5;</code>
     * @return The hasPrevious.
     */
    @java.lang.Override
    public boolean getHasPrevious() {
      return hasPrevious_;
    }

    public static final int NEXT_CURSOR_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nextCursor_ = "";
    /**
     * <pre>
     * Next cursor for pagination
     * </pre>
     *
     * <code>string next_cursor = 6;</code>
     * @return The nextCursor.
     */
    @java.lang.Override
    public java.lang.String getNextCursor() {
      java.lang.Object ref = nextCursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextCursor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Next cursor for pagination
     * </pre>
     *
     * <code>string next_cursor = 6;</code>
     * @return The bytes for nextCursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextCursorBytes() {
      java.lang.Object ref = nextCursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextCursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREV_CURSOR_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object prevCursor_ = "";
    /**
     * <pre>
     * Previous cursor for pagination
     * </pre>
     *
     * <code>string prev_cursor = 7;</code>
     * @return The prevCursor.
     */
    @java.lang.Override
    public java.lang.String getPrevCursor() {
      java.lang.Object ref = prevCursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prevCursor_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Previous cursor for pagination
     * </pre>
     *
     * <code>string prev_cursor = 7;</code>
     * @return The bytes for prevCursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrevCursorBytes() {
      java.lang.Object ref = prevCursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prevCursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0) {
        output.writeInt32(1, offset_);
      }
      if (limit_ != 0) {
        output.writeInt32(2, limit_);
      }
      if (totalCount_ != 0) {
        output.writeInt32(3, totalCount_);
      }
      if (hasNext_ != false) {
        output.writeBool(4, hasNext_);
      }
      if (hasPrevious_ != false) {
        output.writeBool(5, hasPrevious_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextCursor_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nextCursor_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prevCursor_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, prevCursor_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limit_);
      }
      if (totalCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalCount_);
      }
      if (hasNext_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasNext_);
      }
      if (hasPrevious_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, hasPrevious_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextCursor_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nextCursor_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prevCursor_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, prevCursor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sonet.common.PaginationOuterClass.PaginationResponse)) {
        return super.equals(obj);
      }
      sonet.common.PaginationOuterClass.PaginationResponse other = (sonet.common.PaginationOuterClass.PaginationResponse) obj;

      if (getOffset()
          != other.getOffset()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (getTotalCount()
          != other.getTotalCount()) return false;
      if (getHasNext()
          != other.getHasNext()) return false;
      if (getHasPrevious()
          != other.getHasPrevious()) return false;
      if (!getNextCursor()
          .equals(other.getNextCursor())) return false;
      if (!getPrevCursor()
          .equals(other.getPrevCursor())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCount();
      hash = (37 * hash) + HAS_NEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasNext());
      hash = (37 * hash) + HAS_PREVIOUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPrevious());
      hash = (37 * hash) + NEXT_CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getNextCursor().hashCode();
      hash = (37 * hash) + PREV_CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getPrevCursor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.PaginationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sonet.common.PaginationOuterClass.PaginationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Pagination response information
     * </pre>
     *
     * Protobuf type {@code sonet.common.PaginationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonet.common.PaginationResponse)
        sonet.common.PaginationOuterClass.PaginationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sonet.common.PaginationOuterClass.PaginationResponse.class, sonet.common.PaginationOuterClass.PaginationResponse.Builder.class);
      }

      // Construct using sonet.common.PaginationOuterClass.PaginationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        offset_ = 0;
        limit_ = 0;
        totalCount_ = 0;
        hasNext_ = false;
        hasPrevious_ = false;
        nextCursor_ = "";
        prevCursor_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_PaginationResponse_descriptor;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationResponse getDefaultInstanceForType() {
        return sonet.common.PaginationOuterClass.PaginationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationResponse build() {
        sonet.common.PaginationOuterClass.PaginationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.PaginationResponse buildPartial() {
        sonet.common.PaginationOuterClass.PaginationResponse result = new sonet.common.PaginationOuterClass.PaginationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sonet.common.PaginationOuterClass.PaginationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.offset_ = offset_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalCount_ = totalCount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hasNext_ = hasNext_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hasPrevious_ = hasPrevious_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.nextCursor_ = nextCursor_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.prevCursor_ = prevCursor_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sonet.common.PaginationOuterClass.PaginationResponse) {
          return mergeFrom((sonet.common.PaginationOuterClass.PaginationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sonet.common.PaginationOuterClass.PaginationResponse other) {
        if (other == sonet.common.PaginationOuterClass.PaginationResponse.getDefaultInstance()) return this;
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getTotalCount() != 0) {
          setTotalCount(other.getTotalCount());
        }
        if (other.getHasNext() != false) {
          setHasNext(other.getHasNext());
        }
        if (other.getHasPrevious() != false) {
          setHasPrevious(other.getHasPrevious());
        }
        if (!other.getNextCursor().isEmpty()) {
          nextCursor_ = other.nextCursor_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getPrevCursor().isEmpty()) {
          prevCursor_ = other.prevCursor_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                offset_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                limit_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalCount_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                hasNext_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                hasPrevious_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                nextCursor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                prevCursor_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return The limit.
       */
      @java.lang.Override
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        limit_ = 0;
        onChanged();
        return this;
      }

      private int totalCount_ ;
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @return The totalCount.
       */
      @java.lang.Override
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @param value The totalCount to set.
       * @return This builder for chaining.
       */
      public Builder setTotalCount(int value) {
        
        totalCount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalCount_ = 0;
        onChanged();
        return this;
      }

      private boolean hasNext_ ;
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @return The hasNext.
       */
      @java.lang.Override
      public boolean getHasNext() {
        return hasNext_;
      }
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @param value The hasNext to set.
       * @return This builder for chaining.
       */
      public Builder setHasNext(boolean value) {
        
        hasNext_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasNext() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasNext_ = false;
        onChanged();
        return this;
      }

      private boolean hasPrevious_ ;
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @return The hasPrevious.
       */
      @java.lang.Override
      public boolean getHasPrevious() {
        return hasPrevious_;
      }
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @param value The hasPrevious to set.
       * @return This builder for chaining.
       */
      public Builder setHasPrevious(boolean value) {
        
        hasPrevious_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasPrevious() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasPrevious_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object nextCursor_ = "";
      /**
       * <pre>
       * Next cursor for pagination
       * </pre>
       *
       * <code>string next_cursor = 6;</code>
       * @return The nextCursor.
       */
      public java.lang.String getNextCursor() {
        java.lang.Object ref = nextCursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nextCursor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Next cursor for pagination
       * </pre>
       *
       * <code>string next_cursor = 6;</code>
       * @return The bytes for nextCursor.
       */
      public com.google.protobuf.ByteString
          getNextCursorBytes() {
        java.lang.Object ref = nextCursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nextCursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Next cursor for pagination
       * </pre>
       *
       * <code>string next_cursor = 6;</code>
       * @param value The nextCursor to set.
       * @return This builder for chaining.
       */
      public Builder setNextCursor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nextCursor_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Next cursor for pagination
       * </pre>
       *
       * <code>string next_cursor = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNextCursor() {
        nextCursor_ = getDefaultInstance().getNextCursor();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Next cursor for pagination
       * </pre>
       *
       * <code>string next_cursor = 6;</code>
       * @param value The bytes for nextCursor to set.
       * @return This builder for chaining.
       */
      public Builder setNextCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nextCursor_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object prevCursor_ = "";
      /**
       * <pre>
       * Previous cursor for pagination
       * </pre>
       *
       * <code>string prev_cursor = 7;</code>
       * @return The prevCursor.
       */
      public java.lang.String getPrevCursor() {
        java.lang.Object ref = prevCursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prevCursor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Previous cursor for pagination
       * </pre>
       *
       * <code>string prev_cursor = 7;</code>
       * @return The bytes for prevCursor.
       */
      public com.google.protobuf.ByteString
          getPrevCursorBytes() {
        java.lang.Object ref = prevCursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prevCursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Previous cursor for pagination
       * </pre>
       *
       * <code>string prev_cursor = 7;</code>
       * @param value The prevCursor to set.
       * @return This builder for chaining.
       */
      public Builder setPrevCursor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        prevCursor_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Previous cursor for pagination
       * </pre>
       *
       * <code>string prev_cursor = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevCursor() {
        prevCursor_ = getDefaultInstance().getPrevCursor();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Previous cursor for pagination
       * </pre>
       *
       * <code>string prev_cursor = 7;</code>
       * @param value The bytes for prevCursor to set.
       * @return This builder for chaining.
       */
      public Builder setPrevCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        prevCursor_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sonet.common.PaginationResponse)
    }

    // @@protoc_insertion_point(class_scope:sonet.common.PaginationResponse)
    private static final sonet.common.PaginationOuterClass.PaginationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sonet.common.PaginationOuterClass.PaginationResponse();
    }

    public static sonet.common.PaginationOuterClass.PaginationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaginationResponse>
        PARSER = new com.google.protobuf.AbstractParser<PaginationResponse>() {
      @java.lang.Override
      public PaginationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PaginationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaginationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sonet.common.PaginationOuterClass.PaginationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PaginationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonet.common.Pagination)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    int getOffset();

    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    int getLimit();

    /**
     * <pre>
     * Total number of items available
     * </pre>
     *
     * <code>int32 total_count = 3;</code>
     * @return The totalCount.
     */
    int getTotalCount();

    /**
     * <pre>
     * Whether there are more items available
     * </pre>
     *
     * <code>bool has_next = 4;</code>
     * @return The hasNext.
     */
    boolean getHasNext();

    /**
     * <pre>
     * Whether there are previous items available
     * </pre>
     *
     * <code>bool has_previous = 5;</code>
     * @return The hasPrevious.
     */
    boolean getHasPrevious();
  }
  /**
   * <pre>
   * Legacy pagination information for API responses
   * </pre>
   *
   * Protobuf type {@code sonet.common.Pagination}
   */
  public static final class Pagination extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sonet.common.Pagination)
      PaginationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pagination.newBuilder() to construct.
    private Pagination(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pagination() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pagination();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_Pagination_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sonet.common.PaginationOuterClass.internal_static_sonet_common_Pagination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sonet.common.PaginationOuterClass.Pagination.class, sonet.common.PaginationOuterClass.Pagination.Builder.class);
    }

    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_ = 0;
    /**
     * <pre>
     * Number of items to skip
     * </pre>
     *
     * <code>int32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }

    public static final int LIMIT_FIELD_NUMBER = 2;
    private int limit_ = 0;
    /**
     * <pre>
     * Maximum number of items to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }

    public static final int TOTAL_COUNT_FIELD_NUMBER = 3;
    private int totalCount_ = 0;
    /**
     * <pre>
     * Total number of items available
     * </pre>
     *
     * <code>int32 total_count = 3;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }

    public static final int HAS_NEXT_FIELD_NUMBER = 4;
    private boolean hasNext_ = false;
    /**
     * <pre>
     * Whether there are more items available
     * </pre>
     *
     * <code>bool has_next = 4;</code>
     * @return The hasNext.
     */
    @java.lang.Override
    public boolean getHasNext() {
      return hasNext_;
    }

    public static final int HAS_PREVIOUS_FIELD_NUMBER = 5;
    private boolean hasPrevious_ = false;
    /**
     * <pre>
     * Whether there are previous items available
     * </pre>
     *
     * <code>bool has_previous = 5;</code>
     * @return The hasPrevious.
     */
    @java.lang.Override
    public boolean getHasPrevious() {
      return hasPrevious_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (offset_ != 0) {
        output.writeInt32(1, offset_);
      }
      if (limit_ != 0) {
        output.writeInt32(2, limit_);
      }
      if (totalCount_ != 0) {
        output.writeInt32(3, totalCount_);
      }
      if (hasNext_ != false) {
        output.writeBool(4, hasNext_);
      }
      if (hasPrevious_ != false) {
        output.writeBool(5, hasPrevious_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (offset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, offset_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, limit_);
      }
      if (totalCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalCount_);
      }
      if (hasNext_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasNext_);
      }
      if (hasPrevious_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, hasPrevious_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sonet.common.PaginationOuterClass.Pagination)) {
        return super.equals(obj);
      }
      sonet.common.PaginationOuterClass.Pagination other = (sonet.common.PaginationOuterClass.Pagination) obj;

      if (getOffset()
          != other.getOffset()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (getTotalCount()
          != other.getTotalCount()) return false;
      if (getHasNext()
          != other.getHasNext()) return false;
      if (getHasPrevious()
          != other.getHasPrevious()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getOffset();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCount();
      hash = (37 * hash) + HAS_NEXT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasNext());
      hash = (37 * hash) + HAS_PREVIOUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPrevious());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sonet.common.PaginationOuterClass.Pagination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sonet.common.PaginationOuterClass.Pagination prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Legacy pagination information for API responses
     * </pre>
     *
     * Protobuf type {@code sonet.common.Pagination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonet.common.Pagination)
        sonet.common.PaginationOuterClass.PaginationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_Pagination_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_Pagination_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sonet.common.PaginationOuterClass.Pagination.class, sonet.common.PaginationOuterClass.Pagination.Builder.class);
      }

      // Construct using sonet.common.PaginationOuterClass.Pagination.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        offset_ = 0;
        limit_ = 0;
        totalCount_ = 0;
        hasNext_ = false;
        hasPrevious_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sonet.common.PaginationOuterClass.internal_static_sonet_common_Pagination_descriptor;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.Pagination getDefaultInstanceForType() {
        return sonet.common.PaginationOuterClass.Pagination.getDefaultInstance();
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.Pagination build() {
        sonet.common.PaginationOuterClass.Pagination result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sonet.common.PaginationOuterClass.Pagination buildPartial() {
        sonet.common.PaginationOuterClass.Pagination result = new sonet.common.PaginationOuterClass.Pagination(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sonet.common.PaginationOuterClass.Pagination result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.offset_ = offset_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.totalCount_ = totalCount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.hasNext_ = hasNext_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.hasPrevious_ = hasPrevious_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sonet.common.PaginationOuterClass.Pagination) {
          return mergeFrom((sonet.common.PaginationOuterClass.Pagination)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sonet.common.PaginationOuterClass.Pagination other) {
        if (other == sonet.common.PaginationOuterClass.Pagination.getDefaultInstance()) return this;
        if (other.getOffset() != 0) {
          setOffset(other.getOffset());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        if (other.getTotalCount() != 0) {
          setTotalCount(other.getTotalCount());
        }
        if (other.getHasNext() != false) {
          setHasNext(other.getHasNext());
        }
        if (other.getHasPrevious() != false) {
          setHasPrevious(other.getHasPrevious());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                offset_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                limit_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                totalCount_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                hasNext_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                hasPrevious_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return The offset.
       */
      @java.lang.Override
      public int getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of items to skip
       * </pre>
       *
       * <code>int32 offset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return The limit.
       */
      @java.lang.Override
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Maximum number of items to return
       * </pre>
       *
       * <code>int32 limit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        limit_ = 0;
        onChanged();
        return this;
      }

      private int totalCount_ ;
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @return The totalCount.
       */
      @java.lang.Override
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @param value The totalCount to set.
       * @return This builder for chaining.
       */
      public Builder setTotalCount(int value) {
        
        totalCount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Total number of items available
       * </pre>
       *
       * <code>int32 total_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        totalCount_ = 0;
        onChanged();
        return this;
      }

      private boolean hasNext_ ;
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @return The hasNext.
       */
      @java.lang.Override
      public boolean getHasNext() {
        return hasNext_;
      }
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @param value The hasNext to set.
       * @return This builder for chaining.
       */
      public Builder setHasNext(boolean value) {
        
        hasNext_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether there are more items available
       * </pre>
       *
       * <code>bool has_next = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasNext() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasNext_ = false;
        onChanged();
        return this;
      }

      private boolean hasPrevious_ ;
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @return The hasPrevious.
       */
      @java.lang.Override
      public boolean getHasPrevious() {
        return hasPrevious_;
      }
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @param value The hasPrevious to set.
       * @return This builder for chaining.
       */
      public Builder setHasPrevious(boolean value) {
        
        hasPrevious_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether there are previous items available
       * </pre>
       *
       * <code>bool has_previous = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasPrevious() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasPrevious_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sonet.common.Pagination)
    }

    // @@protoc_insertion_point(class_scope:sonet.common.Pagination)
    private static final sonet.common.PaginationOuterClass.Pagination DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sonet.common.PaginationOuterClass.Pagination();
    }

    public static sonet.common.PaginationOuterClass.Pagination getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pagination>
        PARSER = new com.google.protobuf.AbstractParser<Pagination>() {
      @java.lang.Override
      public Pagination parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pagination> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pagination> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sonet.common.PaginationOuterClass.Pagination getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sonet_common_PaginationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sonet_common_PaginationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sonet_common_PaginationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sonet_common_PaginationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sonet_common_Pagination_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sonet_common_Pagination_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027common/pagination.proto\022\014sonet.common\"" +
      "B\n\021PaginationRequest\022\016\n\006offset\030\001 \001(\005\022\r\n\005" +
      "limit\030\002 \001(\005\022\016\n\006cursor\030\003 \001(\t\"\232\001\n\022Paginati" +
      "onResponse\022\016\n\006offset\030\001 \001(\005\022\r\n\005limit\030\002 \001(" +
      "\005\022\023\n\013total_count\030\003 \001(\005\022\020\n\010has_next\030\004 \001(\010" +
      "\022\024\n\014has_previous\030\005 \001(\010\022\023\n\013next_cursor\030\006 " +
      "\001(\t\022\023\n\013prev_cursor\030\007 \001(\t\"h\n\nPagination\022\016" +
      "\n\006offset\030\001 \001(\005\022\r\n\005limit\030\002 \001(\005\022\023\n\013total_c" +
      "ount\030\003 \001(\005\022\020\n\010has_next\030\004 \001(\010\022\024\n\014has_prev" +
      "ious\030\005 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sonet_common_PaginationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sonet_common_PaginationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sonet_common_PaginationRequest_descriptor,
        new java.lang.String[] { "Offset", "Limit", "Cursor", });
    internal_static_sonet_common_PaginationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sonet_common_PaginationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sonet_common_PaginationResponse_descriptor,
        new java.lang.String[] { "Offset", "Limit", "TotalCount", "HasNext", "HasPrevious", "NextCursor", "PrevCursor", });
    internal_static_sonet_common_Pagination_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sonet_common_Pagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sonet_common_Pagination_descriptor,
        new java.lang.String[] { "Offset", "Limit", "TotalCount", "HasNext", "HasPrevious", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
